-- Custom commands for PTR
UPDATE `command` SET `security`='2' WHERE `name`='gm visible';
UPDATE `command` SET `security`='2' WHERE `name`='gm';
UPDATE `command` SET `security`='2' WHERE `name`='learn';
UPDATE `command` SET `security`='2' WHERE `name`='modify hp';
UPDATE `command` SET `security`='2' WHERE `name`='modify mana';
UPDATE `command` SET `security`='2' WHERE `name`='modify rage';
UPDATE `command` SET `security`='2' WHERE `name`='modify energy';
UPDATE `command` SET `security`='2' WHERE `name`='modify money';
UPDATE `command` SET `security`='2' WHERE `name`='modify scale';
UPDATE `command` SET `security`='2' WHERE `name`='modify faction';
UPDATE `command` SET `security`='2' WHERE `name`='modify tp';
UPDATE `command` SET `security`='2' WHERE `name`='modify mount';
UPDATE `command` SET `security`='2' WHERE `name`='modify honor';
UPDATE `command` SET `security`='2' WHERE `name`='modify rep';
UPDATE `command` SET `security`='2' WHERE `name`='modify standstate';
UPDATE `command` SET `security`='2' WHERE `name`='modify morph';
UPDATE `command` SET `security`='2' WHERE `name`='modify gender';
UPDATE `command` SET `security`='2' WHERE `name`='npc add';
UPDATE `command` SET `security`='2' WHERE `name`='npc additem';
UPDATE `command` SET `security`='2' WHERE `name`='npc delete';
UPDATE `command` SET `security`='2' WHERE `name`='npc addweapon';
UPDATE `command` SET `security`='2' WHERE `name`='cooldown';
UPDATE `command` SET `security`='2' WHERE `name`='unlearn';
UPDATE `command` SET `security`='2' WHERE `name`='levelup';
UPDATE `command` SET `security`='2' WHERE `name`='additem';
UPDATE `command` SET `security`='2' WHERE `name`='setskill';
UPDATE `command` SET `security`='6' WHERE `name`='pinfo';
UPDATE `command` SET `security`='2' WHERE `name`='respawn';
UPDATE `command` SET `security`='4' WHERE `name`='unmute';
UPDATE `command` SET `security`='2' WHERE `name`='damage';
UPDATE `command` SET `security`='2' WHERE `name`='aura';
UPDATE `command` SET `security`='2' WHERE `name`='gobject';
UPDATE `command` SET `security`='2' WHERE `name`='gobject add';
UPDATE `command` SET `security`='2' WHERE `name`='gobject delete';
UPDATE `command` SET `security`='2' WHERE `name`='gobject move';
UPDATE `command` SET `security`='2' WHERE `name`='quest';
UPDATE `command` SET `security`='2' WHERE `name`='quest add';
UPDATE `command` SET `security`='2' WHERE `name`='quest delete';
UPDATE `command` SET `security`='2' WHERE `name`='unbind';
UPDATE `command` SET `security`='2' WHERE `name`='unbind all';
UPDATE `command` SET `security`='2' WHERE `name`='aura';
UPDATE `command` SET `security`='2' WHERE `name`='unaura';
UPDATE `command` SET `security`='2' WHERE `name`='unaura all';
UPDATE `command` SET `security`='2' WHERE `name`='learn';
UPDATE `command` SET `security`='2' WHERE `name`='instance';
UPDATE `command` SET `security`='2' WHERE `name`='instance unbind';
UPDATE `command` SET `security`='2' WHERE `name`='damage';